[package]
name = "blackjack"
version = "0.1.0"
authors = ["sendai0905 <coom_st@ruri.waseda.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = '0.7.0'